---
name: Neat Starter
baseUrl: 'https://www.mysite.com'
en:
  metaTitle: Title in english
  metaDescription: Description in english
fr:
  metaTitle: Titre en français
  metaDescription: Description en français
